#Common-Crawl CDX Server Config
archive_paths: https:/s3.amazonaws.com/commoncrawl
#archive_paths: s3://commoncrawl/

# suffix to add to collection for cdx api
enable_cdx_api: -index

enable_memento: true

shard_index_loc:
    match: '.*(collections/[^/]+/)'
    replace: 'https://s3.amazonaws.com/commoncrawl/cc-index/\1'
    #replace: 's3://commoncrawl/cc-index/\1'

# this is also the default page size
max_blocks: 5

# disable framed replay mode
framed_replay: false

